name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: scripts/check
        shell: bash
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: configure git
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
        shell: bash
      - name: stage release
        run: scripts/stage_release
        shell: bash
      - name: commit & push
        run: |
          git commit -m"Release ${{ github.ref_name }}@${{ github.sha }}"
          git push origin release
          # Leave the repo on the main branch so that github 
          # can find .github/actions to tear down
          git checkout main
        shell: bash
      - name: npm publish
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd npm && npm publish
